#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo Usage: ./install_website username
  echo
  echo username is your user name on rick.logic.at and finn.logic.at
  exit 1
fi
# we cannot use jump hosts to connect to finn.logic.at via rick.logic.at
# as finn.logic.at does not provide shell access
# thus we upload the website into a temporary directory on rick and run
# the sftp script from there
remote_temp_dir="/tmp/gapt-website-$$"
scp $(git ls-files) "$1@rick.logic.at:$remote_temp_dir/"
ssh $1@rick.logic.at "cd $remote_temp_dir; sftp -b install_website.sftp-batch $1@finn.logic.at; rm -rf $remote_temp_dir"
