#!/bin/bash
#
# execute this from your logic.at account to install the website
#
DESTDIR=/home/httpd/html/gapt

install -m664 index.html logo.png style.css valid-html401.png $DESTDIR/
install -m664 downloads/index.html $DESTDIR/downloads/
